# Generated by Django 3.2.5 on 2021-07-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='backgruond_url',
            new_name='background_url',
        ),
    ]
